### PR TITLE
KOUNT-104 Add updated module name to Kount_Kount and remove all swarming namespaces

### PR DESCRIPTION
**Pull request by jcolas15**

### CODE REVIEW

**Comment by toddfunke** [comment]
The namespace change to kount/kount is redundant.  Can swarming just be removed?

For example:
Instead of replacing swarming\kount to kount\kount, can this just be kount?

**Review by OleksandrTykhonov — APPROVED** [review]

**Comment by jcolas15** [comment]
> The namespace change to kount/kount is redundant. Can swarming just be removed?
> 
> For example:
> Instead of replacing swarming\kount to kount\kount, can this just be kount?

Hey @toddfunke, we can rename it to something else, but we cannot name it just kount since the format is "<vendor_name>"/"<module_name>". If you would like a different module name, we can do that too.  Something like kount/kount-ris can also be done.

**Comment by toddfunke** [comment]
@jcolas15,

Thanks for the clarification.  I thought that might be the case.  For now, let's just leave this as kount/kount.  

Thanks,

Todd

**Comment by toddfunke** [comment]
@jcolas15,

This is ready to merge, can you merge it?

Thanks,

Todd

**Comment by jcolas15** [comment]
Hey @toddfunke 

This is done.  First module version 0.1.0

Jon

**Pull request merged**
